DELIMITER $$

ALTER DEFINER=`root`@`localhost` EVENT `EVENT_AUTO_CANCEL_PEMINJAMAN` ON SCHEDULE EVERY 1 DAY STARTS '2017-07-11 00:00:00' ENDS '2023-11-30 00:00:00' ON COMPLETION NOT PRESERVE ENABLE DO UPDATE SIMA_PEMINJAMAN_TR
SET SIMA_PEMINJAMAN_TR.N_STATUS_PEMINJAMAN='5'
WHERE SIMA_PEMINJAMAN_TR.N_STATUS_PEMINJAMAN='2' AND SIMA_PEMINJAMAN_TR.DT_WAKTU_EXPIRE < NOW()$$

DELIMITER ;