CREATE TABLE `sima_template_surat_mt` (
  `ID_TEMPLATE` int(11) NOT NULL AUTO_INCREMENT,
  `V_NAMA_TEMPLATE` varchar(45) NOT NULL,
  `V_ISI_TEMPLATE` text,
  PRIMARY KEY (`ID_TEMPLATE`),
  UNIQUE KEY `V_NAMA_TEMPLATE_UNIQUE` (`V_NAMA_TEMPLATE`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1